// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xisvzchvmcqeqtkxoecr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpc3Z6Y2h2bWNxZXF0a3hvZWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzU1MTEsImV4cCI6MjA2ODE1MTUxMX0.OYbyWFSd9ZXcvuZirDmuxrKHAlqZ3Xa-EGGP8CEGn44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});